module.exports.IPATABLE = {
    'b': ['C-pot,bet,mom'],
    'ɑ': ['V-bought'],
    't': ['C-dog,top,nod'],
    'ð': ['C-thick,that'],
    'ə': ['V-beat'],
    'k': ['C-kit,got,thing'],
    'w': ['C-won V-boot'],
    'ɪ': ['C-you V-bit'],
    'eɪ': ['V-bait,bet,book'],
    'ʒ': ['C-shut,church,jump,measure'],
    'f': ['C-fog,vat'],
    's': ['C-sat,zoo'],
    'ʤ': ['C-shut,church,jump,measure'],
    'ʌ': ['V-bat,about,but'],
    'm': ['C-pot,bet,mom'],
    'p': ['C-pot,bet,mom'],
    't': ['C-dog,top,nod'],
    'n': ['C-dog,top,nod'],
    'æ': ['V-bat,about,but'],
    'e': ['V-bait,bet,book'],
    'ɚ': ['V-bird'],
    'o': ['V-boat'],
    'v': ['C-fog,vat'],
    'i': ['V-beat'],
    'tʃ': ['C-shut,church,jump,measure'],
    'θ': ['C-thick,that'],
    'd': ['C-dog,top,nod'],
    'g': ['C-kit,got,thing'],
    'l': ['C-lot'],
    'ʊ': ['V-bait,bet,book'],
    'aʊ': ['V-brown 1', 'V-brown 2'],
    'aɪ': ['V-bite 1', 'V-bite 2'],
    'ʃ': ['C-shut,church,jump,measure'],
    'h': ['C-help'],
    'i': ['V-beat'],
    'z': ['C-sat,zoo'],
    'j': ['C-you V-bit'],
    'u': ['C-won V-boot'],
    'ɛ': ['V-bait,bet,book'],
    'r': ['C-rat'],
    'ŋ': ['C-kit,got,thing']
};